### ISSUE TITLE
Issue with the Cops Script - Cop menu not working

### ISSUE THREAD

**Issue by jake240404** [FiveM-Scripts/Cops_FiveM#110]
I presume its just the rolesFX, but i keep backing up my server and the cop menu just wont work when we all press F5, i dont know what this issue is, it works, then i add loads of other scripts, then it just doesn't work

**Comment by Kyominii** [comment]
Are you on duty when you try to press F5 ?

**Comment by Toxikflea** [comment]
could have a conflicting script.

**Comment by Kyominii** [comment]
The author of this bug haven't answered so I assume this bug is resolved
