### ISSUE TITLE
Server.lua not loading.

### ISSUE THREAD

**Issue by Toxikflea** [FiveM-Scripts/Cops_FiveM#114]
Every time i try to load this on my server it says server.lua could not load or something like that for reference here is a pic. 
![image](https://user-images.githubusercontent.com/32425096/37264719-0d9eb47c-257d-11e8-898a-24c2afa6f0d1.png)

**Comment by Toxikflea** [comment]
I am re-downloading MySQL.

**Comment by ghermans** [comment]
This issue is caused because you did not installed [mysql-async](https://github.com/brouznouf/fivem-mysql-async).
