### ISSUE TITLE
server/server.lua still not loading

### ISSUE THREAD

**Issue by Toxikflea** [FiveM-Scripts/Cops_FiveM#115]
I have filled this out once before and the guy closed it with out helping to fix it.

![image](https://user-images.githubusercontent.com/32425096/37265853-3ea0fd44-2584-11e8-9adb-1070016e6d76.png)

**Comment by ghermans** [comment]
as i answered before in #114 , you did not installed mysql-async in the correct way, read the README file from mysql-async and your issue will be resolved.
