### ISSUE TITLE
Database query error

### ISSUE THREAD

**Issue by DubStepMad** [FiveM-Scripts/Cops_FiveM#128]
I have put my log test on pastebin since it was full of random stuff.
Information:
Server is home hosted and database is hosted somewhere else since I have a web hosting package which includes a large number of database schemas.
https://pastebin.com/9RK0fnnt

**Comment by ghermans** [comment]
At this point the script isn't working properly with mysql 8.0 try to downgrade your mysql server and your issue should be resolved.
