### ISSUE TITLE
Cant clock in

### ISSUE THREAD

**Issue by michaelweske** [FiveM-Scripts/Cops_FiveM#131]
When I go to clock in I can only clock out

**Comment by ghermans** [comment]
You need to define a department for your player
1. Use the chat command **/copdept** 
```
/copdept ID Department 
```
You can find the available department id's [here](https://github.com/FiveM-Scripts/Cops_FiveM#departments)

**Comment by michaelweske** [comment]
I did Im ranked and in a department aswell as cop admin

**Comment by ghermans** [comment]
Walk away from the cloakroom marker, then go back .    
If that does not work exit FiveM and reconnect to your server.

**Comment by michaelweske** [comment]
Never mind I fixed it my server had a fucking stroke and wiped my SQL data
