### ISSUE TITLE
No Such Command for CopAddAdmin

### ISSUE THREAD

**Issue by 320thSTSMilSim** [FiveM-Scripts/Cops_FiveM#132]
Hello,

I followed the directions to the letter, but it keeps giving me No Such Command for the CopAddAdmin command. I put it in just like that. I do have it in the resources and on my server config as when I do stop and start command in rcon, it says stopped and started. Not sure why it's not picking up on the command. Please help.

**Comment by ghermans** [comment]
It looks like the script didn't start on your server.

1. Could you verify that you only copied the **police subfolder** to your resources folder?
2. Verify your server console for any other errors above `No Such Command for the CopAddAdmin`.
3. Optional: verify if the script created the database tables.

**Comment by 320thSTSMilSim** [comment]
1. I do have it in a subfolder for custom scripts. Would that matter?
2. No other erros.
3. It has not created the DB tables. Is there anything in the script I need to change or just the `set mysql_connection_string "server=localhost;database=gtavrp;userid=root;password=(removed)"`

**Comment by ghermans** [comment]
- I would advise to use the path that the documentation says -> **resources/police**
- Your server.cfg file should look like this

```
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

set mysql_connection_string "server=127.0.0.1;database=DBNAME;userid=DBUSER;password=DBPASS;"

start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start playernames
start mysql-async
start police
etc.....
```

**Comment by 320thSTSMilSim** [comment]
Ok I moved the police folder over to resources only, no subfolder. Still No Such Command error. 

Here's what my server.cfg looks like

`endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

set mysql_connection_string "server=localhost;database=DBNAME;userid=root;password=DBPASS"

start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start playernames
start map

#custom scripts
start mysql-async
start police

**Comment by ghermans** [comment]
Don't see any issues above unless there is a framework involved inside CustomScripts like for example vrp.

**Comment by 320thSTSMilSim** [comment]
Hmm, tried disabling that resource of Custom Scripts, still getting error. I still don't see the DB Tables being created either.

**Comment by ghermans** [comment]
- Verify that the folder for mysql-async in your resource folder = **mysql-async** not mysql-async-master or something else.
- Also if the db table is not created then there should be a error in your server console.
- Else try a fresh install with only mysql-async & Cops_FiveM without adding any other resources and see if that works.

**Comment by 320thSTSMilSim** [comment]
Well, unfortunately, looks like I'll be unable to use the script. Fresh install and still won't work. Won't create the DB tables and commands won't work. Zero errors, so nothing saying wrong db info or anything. Too bad, looks like a great script. Maybe make another copy of the script that doesn't require a database where we can add players in by steam identifier and keep everything in a permissions file? Just a suggestion. You can close this as I'm not gonna mess with it anymore, just getting too frustrated over it.

**Comment by ghermans** [comment]
Still it looks there is something wrong with your setup since this isn't a bug.
