### ISSUE TITLE
Cannot add myself or anyone to the data base 

### ISSUE THREAD

**Issue by SirOric** [FiveM-Scripts/Cops_FiveM#133]
when I try /copadd ID I get a Government: you don't have the permission to execute this task.
also when I try the CopAddAdmin 1 in the console I get MySQL-async.js:209563: uncaught type error: cannot convert undefined or null object.

any pointers anyone?

Thanks,
Eric

**Comment by ghermans** [comment]
Thanks for reporting this issue, it seems that this error occurs after a recent update from mysql-async.    
We will investigate this and provide a fix asap.

**Comment by ghermans** [comment]
This issue should be resolved with the [recent update](https://github.com/FiveM-Scripts/Cops_FiveM/releases/latest).
