### ISSUE TITLE
Criminal DB/Web-based dashboard

### ISSUE THREAD

**Issue by Kyominii** [FiveM-Scripts/Cops_FiveM#14]
having a criminal db which can be accessed by cops

**Comment by ASimpson87** [comment]
I've done this so cops can enter into database and is read-able through browser , will add in-game veiwer later.

**config.lua**
**line 149**

`		menu_crimedb_title = "Do paperwork",`

**menupolice.lua
**line 153**** 
```

		elseif btn == txt[config.lang]["menu_crimedb_title"]  then 	
			CriminalDB()

```


**line 327**

```
function CriminalDB()
	local crime = ''
	local t, distance = GetClosestPlayer()
	if(distance ~= -1 and distance < 3) then
			DisplayOnscreenKeyboard(1, "FMMC_KEY_TIP8S", "", "", "", "", "", 128)
			while (UpdateOnscreenKeyboard() == 0) do
				DisableAllControlActions(0);
				Wait(0);
			end
			if (GetOnscreenKeyboardResult()) then
				local res = GetOnscreenKeyboardResult()
				if(string.len(res) > 0) then
				crime = res				
				end
			end
			TriggerServerEvent("police:addCriminalHistory", GetPlayerServerId(t), crime)
	else
		TriggerEvent('chatMessage', txt[config.lang]["title_notification"], {255, 0, 0}, txt[config.lang]["no_player_near_ped"])
	end
end

```

**server.lua 
line 247**

`RegisterServerEvent('police:addCriminalHistory')
AddEventHandler('police:addCriminalHistory', function(target, crime)
	local ts = os.time()
	print(os.date('%Y-%m-%d %H:%M:%S', ts))
	local player = GetPlayerName(target)
	--TriggerClientEvent("police:notify", source, "CHAR_ANDREAS", 1, txt[config.lang]["title_notification"], false, txt[config.lang]["send_fine_request_part_1"]..amount..txt[config.lang]["send_fine_request_part_2"]..GetPlayerName(target))
    	MySQL:executeQuery("INSERT INTO user_criminaldb (name,crime,time) VALUES ('@username','@crime','@time')",
				{['@username'] = player, ['@crime'] = crime,  ['@time'] = os.date('%Y-%m-%d %H:%M:%S', ts)})
end)
`

import into SQL 

```
-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 08, 2017 at 08:23 AM
-- Server version: 10.1.21-MariaDB
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `gta5_gamemode_essential`
--

-- --------------------------------------------------------

--
-- Table structure for table `user_criminaldb`
--

CREATE TABLE `user_criminaldb` (
  `name` varchar(255) NOT NULL,
  `crime` varchar(255) NOT NULL,
  `time` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

```
Sorry i havent done this for async or couchDB.
Up to you if you want to use it for 1.3 ... i'll look at finishing the viewer in the next few days.

**Comment by Kyominii** [comment]
I have already started this feature ^^'

**Comment by ASimpson87** [comment]
Ok no problem.

**Comment by Kyominii** [comment]
Dashboard will be developed with NodeJS (install with Docker)

**Comment by ghermans** [comment]
## First progress 

![portaluntitled](https://user-images.githubusercontent.com/1594411/39165882-f76049e2-4786-11e8-9f49-7a127fd8cb84.png)

![criminals](https://user-images.githubusercontent.com/1594411/39165881-f7440408-4786-11e8-9cfa-2686d43605ee.png)
