### ISSUE TITLE
Keep mysql-async support

### ISSUE THREAD

**Issue by SamBehner** [FiveM-Scripts/Cops_FiveM#142]
I think there should be a version of Cops_FiveM that supports mysql-async, for the people running on linux machines this resource no longer works because you added ghmattimysql, according to the author of the script "Linux has probably some issues with v8. So Linux users cannot come into the comfort of using this library yet"

**Comment by SamBehner** [comment]
Would it be possible to run an older version of the resource? It doesn't seem to work if I try to do one that supports mysql-async, no errors it just says I need to update the resource version. Did I install it wrong or do I _need_ to run the new version for it to work

**Comment by ghermans** [comment]
Could you please verify if you still have the same issue with this the latest version https://github.com/FiveM-Scripts/Cops_FiveM/releases/tag/v1.4.4.4.1

**Comment by SamBehner** [comment]
It wouldn't work because I can't use ghmattimysql would it?

**Comment by ghermans** [comment]
i just did a fresh install on a vagrant box with ubuntu/trusty64

**when starting the box i didn't get any errors.**
```
Started resource sessionmanager
Started resource mapmanager
Started resource spawnmanager
Started gametype Freeroam
Started resource fivem
Started resource hardcap
Started resource rconlog
Started resource ghmattimysql
Started resource police
Authenticating server license key...
Server license key authentication succeeded. Welcome!
cfx> Started map fivem-map-hipster
Started resource fivem-map-hipster
```

Commands work fine
``` 
cfx> copadd 1
Adding record for player to the database
```
![20181021023433_1](https://user-images.githubusercontent.com/1594411/47261923-4aeff900-d4da-11e8-9ace-e615ca1b5eeb.jpg)

Verified going on duty and no issues either
![20181021023510_1](https://user-images.githubusercontent.com/1594411/47261931-63601380-d4da-11e8-82a6-6e9289762eec.jpg)
![20181021023518_1](https://user-images.githubusercontent.com/1594411/47261932-63f8aa00-d4da-11e8-81e9-001685ebafa3.jpg)

**Comment by SamBehner** [comment]
Oh, ok, based off of the ghmattimysql forum post it doesn't work on linux machines, ill try it out

**Comment by SamBehner** [comment]
Yep it works, thanks :D
