### ISSUE TITLE
Error cant load resource?

### ISSUE THREAD

**Issue by leepafc2** [FiveM-Scripts/Cops_FiveM#143]
Hi I have added everything that is possible, for some reason it wont work on my server. When I use zap server its fine but when doing a self hosted one, it don't work for some reason? 

Yes I have installed all the requirements etc. 

I can provide a screen shot if needed. I tried contacting discord but no answer.

**Comment by leepafc2** [comment]
Well this has been a month with no reply? Why? I also tried the regarding addon that u need and that wont load in the server, I tried everything to get it working...

**Comment by ghermans** [comment]
For installation issues regarding ghmattimysql please contact the author of it (https://forum.fivem.net/t/ghmattimysql-my-mysql-implementation-for-fivem-1-0-0/82174).
