### ISSUE TITLE
Blue Circle in Locker Room Not There.

### ISSUE THREAD

**Issue by Trooper-Lewis** [FiveM-Scripts/Cops_FiveM#146]
Hello,
I currently am creating a esx server. I installed police esx along with the other esx files that is required to run police esx. I whitelisted myself as a officer and yet when I walk in the police station in the locker room I do not see the blue circle to go on duty. Also in my server command prompt I type CopAdd ID and it said the command is unknown. Can someone help me?

**Comment by ghermans** [comment]
1. [Cops FiveM](https://github.com/FiveM-Scripts/Cops_FiveM) is a standalone resource so police esx / esx/ or any other framework isn't required, either we do not provide support for it.
2. The error you receive in your console that the command is unknown means that the script isn't loaded correctly.

I suggest to verify your server console for any errors.
