### ISSUE TITLE
cannot access f5 while in a vehicle 

### ISSUE THREAD

**Issue by fatplatapus** [FiveM-Scripts/Cops_FiveM#149]
I cant access the f5 menu while in a vehicle, which a problem for doing spike strips and stuff!

**Comment by ghermans** [comment]
i couldn't replicate this issue, what other scripts are you using on your server?

**Comment by fatplatapus** [comment]
sorry for the late response, we are using multiple scripts, to many to list, could you tell me what the issue could be so I can check if I have scripts interfering.

**Comment by ghermans** [comment]
I would suggest to verify if you still have the same issue when you use the **default resources** / **ghmattimysql** and **cops_fivem**.

```
start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start playernames
start ghmattimysql
start police
```
