### ISSUE TITLE
Vehicles and Amory not Listing. Notifications not showing

### ISSUE THREAD

**Issue by JeffReagen** [FiveM-Scripts/Cops_FiveM#151]
Hello.
On the Vehicle and Amory Menus there is nothing showing up on the list of of stuff to spawn in. The menus are working fine just not listing on them to

Also I do not have and notifications popping up at all.

**Comment by ghermans** [comment]
Did you assigned your player to a department?
Try this command in your server console (not ingame chat/console)
```
copdept 1 1 
```

**Comment by JeffReagen** [comment]
I gave myself Admin

**Comment by ghermans** [comment]
That doesn't make any difference as admin rights don't have anything todo with departments.
So again: assign your player to a department with the **copdept** command.
https://github.com/FiveM-Scripts/Cops_FiveM#commands
https://github.com/FiveM-Scripts/Cops_FiveM#departments

```
copdept 1 1 
```
For more info please check

**Comment by JeffReagen** [comment]
still not working. I also made it where you needed to be whitelisted bc everyone could go on duty and now I cant do anything. I cant set myself or anyone to anything

**Comment by ghermans** [comment]
Could you please verify if you still have the same issue with the latest update https://github.com/FiveM-Scripts/Cops_FiveM/releases/latest ?
