### ISSUE TITLE
Add an option in Cloackroom to Clock In without getting into a uniform but still getting weapon loadout.

### ISSUE THREAD

**Issue by fatplatapus** [FiveM-Scripts/Cops_FiveM#154]

**Comment by fatplatapus** [comment]
like just clock in, no automatic change into uniform.

**Comment by ghermans** [comment]
This is already added to 2.0, when you choose the undercover model:  you will get on duty with your current model.

**Comment by ghermans** [comment]
This has been resolved in the latest release https://github.com/FiveM-Scripts/Cops_FiveM/releases/latest
