### ISSUE TITLE
min_rank_set_rank

### ISSUE THREAD

**Issue by aidenlee01** [FiveM-Scripts/Cops_FiveM#155]
Although a player's rank is above the set min_rank_set_rank, the /coprank permission is denied in game. 
![image](https://user-images.githubusercontent.com/23531530/54321351-239fe280-45c7-11e9-877c-e00cef5db749.png)

**Comment by ghermans** [comment]
Use [icecon](https://github.com/icedream/icecon) or your server console to enter the command, instead in game.
