### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Jumpmaster746** [FiveM-Scripts/Cops_FiveM#157]
Maybe a video tutorial on how to install. I really am confused. Video pls.

**Comment by ghermans** [comment]
a [readme file](https://github.com/FiveM-Scripts/Cops_FiveM/blob/master/README.md
) is delivered with the resource that contains all the information you need to setup the script.
Just take the time to read the file and you will be able to install it.

**Comment by Jumpmaster746** [comment]
I have
