### ISSUE TITLE
I Cannot clock in the blue circle does not show

### ISSUE THREAD

**Issue by NotMussy** [FiveM-Scripts/Cops_FiveM#163]
So i have a menu server and whenever i go to the station the blue circle does not show up can you please help

**Comment by cnyncrvr** [comment]
Did you make sure to add your self to the database via the F8 console command "CopAddAdmin 1" ?

**Comment by NotMussy** [comment]
No such command CopAddAdmin

**Comment by cnyncrvr** [comment]
Do you have a an SQL database installed and have ghmattimysql installed and configured to connect to said database ?

**Comment by NotMussy** [comment]
yh but how do i configure them

**Comment by cnyncrvr** [comment]
Are you hosting the server locally or through a provider like Zap Host?

**Comment by NotMussy** [comment]
zap host

**Comment by cnyncrvr** [comment]
Please watch this video https://www.youtube.com/watch?v=4UcC9zNZkFc

**Comment by NotMussy** [comment]
but how do i connect the police thingy

**Comment by NotMussy** [comment]
I got to the database

**Comment by cnyncrvr** [comment]
you have to install and configure ghmattimysql to connect to your database first. then you copy the folder police to from CopsFiveM into your servers resources folder, and edit your server.cfg file to say start ghmattimysql and below that start police

**Comment by NotMussy** [comment]
so where it says user you want me to put the zap hosting username

**Comment by cnyncrvr** [comment]
configure the ghmattimysql config file to match the database name, username, password, port that zap has assigned for SQL to your account

**Comment by NotMussy** [comment]
zap525412-1 so the username would be like this i guess

**Comment by cnyncrvr** [comment]
What ever the user name and password they gave you, I cannot help you with that as I do not have experience with Zap hosting

**Comment by NotMussy** [comment]
still does not work

**Comment by cnyncrvr** [comment]
Have you put the ghmattimysql and police folders in your servers resources directory and added the start commands to your servers cfg file?

**Comment by NotMussy** [comment]
yes

**Comment by cnyncrvr** [comment]
Can you post screen shots of your server starting up

**Comment by cnyncrvr** [comment]
Or join the discord so that perhaps I can attempt to help you further

**Comment by NotMussy** [comment]
![image](https://user-images.githubusercontent.com/50523700/57573392-f46aed80-741e-11e9-9b83-1d1522db4264.png)

**Comment by NotMussy** [comment]
thats the start up

**Comment by cnyncrvr** [comment]
Post a screenshot of your server starting up please

**Comment by NotMussy** [comment]
like the server
server

**Comment by cnyncrvr** [comment]
Yes the console of your server starting

**Comment by NotMussy** [comment]
okay

**Comment by NotMussy** [comment]
![image](https://user-images.githubusercontent.com/50523700/57573454-9985c600-741f-11e9-8c03-b21d04df1a9a.png)

**Comment by NotMussy** [comment]
![image](https://user-images.githubusercontent.com/50523700/57573458-a4d8f180-741f-11e9-9d86-308ab0137128.png)

**Comment by cnyncrvr** [comment]
I need to see where it attempts to actually start ghmatti and police

**Comment by NotMussy** [comment]
![image](https://user-images.githubusercontent.com/50523700/57573554-41e85a00-7421-11e9-856d-e580465ef1cd.png)

**Comment by cnyncrvr** [comment]
now go in game and open your console with the F8 key and type CopAddAdmin 1

**Comment by NotMussy** [comment]
it does not work

**Comment by NotMussy** [comment]
We Got it to work

**Comment by nickgill18** [comment]
This doesn’t work for me ether I get the no such command the blue circles are there but can’t register my self as a cop

**Comment by ghermans** [comment]
@nickgill18 
There can only be 2 reasons why the commands don't work.

1. You disabled the white-listing in config/config.lua (this means that everyone can become a cop)
2. ghmattimysql isn't configured correctly.

Best thing i can suggest is to verify your server console for any errors.
