### ISSUE TITLE
No such export execute in resource ghmattimysql

### ISSUE THREAD

**Issue by galaxy-programming** [FiveM-Scripts/Cops_FiveM#173]
Cops-FiveM doesn't work because of this error

**Comment by ghermans** [comment]
1. Remove your current ghmattimysql folder in case it already exists.
2. Download https://github.com/GHMatti/ghmattimysql/releases/download/1.2.1/ghmattimysql.zip .
3. Extract the zip file and rename the folder to ghmattimysql
4. Go to ghmattimysql/config.json and edit your database name/user/password.
5. Copy / paste the ghmattimysql folder to resources.
6. Open server.cfg and add ensure ghmattimysql.

````
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure fivem
ensure hardcap
ensure rconlog
ensure ghmattimysql
ensure police
````
7. Once all the above steps are completed (re)start your server and try if it works.
