### ISSUE TITLE
Issue when putting players into cars

### ISSUE THREAD

**Issue by Mast3rzz** [FiveM-Scripts/Cops_FiveM#177]
There is an issue where if you try to put a player into a police car through the Police menu, they do not stay in the car, like it does not register that the player is being put in the car (Looks like a rubber band effect, they are in the vehicle for a split second and then they tp out of it). If you can help that be brilliant, thankyou.

**Comment by NickRobinYT** [comment]
Make sure that you are undragging the player before forcing them into the vehicle.
