### ISSUE TITLE
Skin/Outfit

### ISSUE THREAD

**Issue by Slenderslicer99** [FiveM-Scripts/Cops_FiveM#180]
When i clock in almost everything is fine. I can use the menu and get a load out, but when clocking in it doesn't change my outfit. I just stay as the default character. This is also happening with other mods too. So i don't know if it my server files that have skin locked or if i'm just missing something?

EDIT: Only the police officer and undercover skin doesn't work. Both the IAA and FIB when selected change the characters skin. Also when i clock out my skin doesn't change back it stays as either the IAA skin or FIB skin. I don't know if its meant to be like that but if not then that's another problem i'm having.

**Comment by ghermans** [comment]
i can not reproduce this issue, try to redownload the script.
