### ISSUE TITLE
ghmattimysql + police

### ISSUE THREAD

**Issue by Hydra2k** [FiveM-Scripts/Cops_FiveM#182]
[ghmattimysql] [ERROR] connect ETIMEDOUT
[MySQL] [WARNING] [police] [10002ms] CREATE TABLE IF NOT EXISTS `police` (`identifier` varchar(255) COLLATE utf8_unicode_ci NOT NULL,`dept` int(11) NOT NULL DEFAULT '0',`rank` int(11) NOT NULL DEFAULT '0') : []
[MySQL] [ERROR] [police] An error happens for query "CREATE TABLE IF NOT EXISTS `police` (`identifier` varchar(255) COLLATE utf8_unicode_ci NOT NULL,`dept` int(11) NOT NULL DEFAULT '0',`rank` int(11) NOT NULL DEFAULT '0') : []": connect ETIMEDOUT

i have tried making multiple new databases and manually creating the tables

**Comment by ghermans** [comment]
This is not a bug from the script but a server issue.
