### ISSUE TITLE
Adding extra player models 

### ISSUE THREAD

**Issue by thilen123** [FiveM-Scripts/Cops_FiveM#36]
When you go on duty as a cop is there a way to randomize skin ?
for example "s_m_y_sheriff_01", "s_f_y_sheriff_01", "s_m_y_cop_01"

**Comment by Kyominii** [comment]
have a option in the menu to select police models and skins

**Comment by ghermans** [comment]
This is resolved with the latest update since you can configure your models for each departments.
Check **config/cloackroom.lua** for more details.
