### ISSUE TITLE
[enhancement] Garage preview

### ISSUE THREAD

**Issue by ghost** [FiveM-Scripts/Cops_FiveM#75]
Would it be possible to ad a feature so players can preview the vehicle before they spawn it in the garage?

**Comment by Kyominii** [comment]
yeah I think

**Comment by ghermans** [comment]
i added this feature to v2.0 

![20180203000616_1](https://user-images.githubusercontent.com/1594411/36228015-35cbb548-11d3-11e8-9029-8f5595920897.jpg)

**Comment by killzone185** [comment]
Sweet
