### ISSUE TITLE
[enhancement] No clock out on death config.lua option

### ISSUE THREAD

**Issue by ghost** [FiveM-Scripts/Cops_FiveM#77]
Possible to add an option in the config for servers to keep cops clocked in after death.

**Comment by ghermans** [comment]
This request is added to v2.0
When you respawn you will get the same outfit as before you died.

![20180205214419_1](https://user-images.githubusercontent.com/1594411/35830335-29999772-0ac6-11e8-8ec2-a59122647be1.jpg)
