### ISSUE TITLE
Permit ppl to put a player in the vehicle while dragging 

### ISSUE THREAD

**Issue by Kyominii** [FiveM-Scripts/Cops_FiveM#78]
https://forum.fivem.net/t/release-cops-fivem-pre-v1-4-0-09-11-2017/17460/1595?u=kyominii

**Comment by fatplatapus** [comment]
yes pls!

**Comment by fatplatapus** [comment]
could you guys put this in the v2.0 milestone, this is the only thing that I don't like about the script, and think it would be awesome if it got added asap, if you need help getting it done, I can help, I know Lua. @Kyominii @ghermans
