### ISSUE TITLE
Jail

### ISSUE THREAD

**Issue by Kyominii** [FiveM-Scripts/Cops_FiveM#8]
because criminals need to be in jail :v

**Comment by ASimpson87** [comment]
Are you working on this ? If not I'll do it today and submit pull request.

**Comment by Kyominii** [comment]
Go ahead, I didn't have time to begin to work on this :)

**Comment by Kyominii** [comment]
In progress

**Comment by Valderg** [comment]
There is an addon for this that is quite nice, i tried it out and it worked, altered time tables in the GUI and made it restrictive to an area so i could uncuff them and place them in the prison, The only issue with this method is that the prison guards drop automatic weapons that they player can then rdm others with in prison. The only solution i have currently found was to remove the weapons every time they are teleported back to the jailing point (which i set when DistBetween your pos, prison pos > 100 to teleport you back) remove all weapons again, then upon being discharged, remove weapons once more.

**Comment by leepafc2** [comment]
Yeah I would love this as well but not sure how it would work? could some one help me please? Thanks
