### ISSUE TITLE
roles chat issue

### ISSUE THREAD

**Issue by Kyominii** [FiveM-Scripts/Cops_FiveM#98]
make cops compatible with roles scripts

**Comment by ghermans** [comment]
@Kyominii  what roles script are talking about?

**Comment by Kyominii** [comment]
Some users told me that they have issues with RolesFX

**Comment by ghermans** [comment]
Do you have any errors available or what is the issue people are experiencing ?

**Comment by Kyominii** [comment]
Yes, it seems people who have this issue have their message twice on the chat

**Comment by ghermans** [comment]
chat roles are deprecated in 2.0
